name: py2
channels:
- defaults
dependencies:
- backports=1.0=py27h63c9359_1
- backports.functools_lru_cache=1.4=py27he8db605_1
- backports.shutil_get_terminal_size=1.0.0=py27h5bc021e_2
- backports.weakref=1.0rc1=py27_0
- backports_abc=0.5=py27h7b3c97b_0
- bleach=1.5.0=py27_0
- ca-certificates=2017.08.26=h1d4fec5_0
- certifi=2017.7.27.1=py27h9ceb091_0
- configparser=3.5.0=py27h5117587_0
- cycler=0.10.0=py27hc7354d3_0
- dbus=1.10.22=h3b5a359_0
- decorator=4.1.2=py27h1544723_0
- entrypoints=0.2.3=py27h502b47d_2
- enum34=1.1.6=py27h99a27e9_1
- expat=2.2.4=hc00ebd1_1
- fontconfig=2.12.4=h88586e7_1
- freetype=2.8=h52ed37b_0
- funcsigs=1.0.2=py27h83f16ab_0
- functools32=3.2.3.2=py27h4ead58f_1
- glib=2.53.6=hc861d11_1
- gmp=6.1.2=hb3b607b_0
- gst-plugins-base=1.12.2=he3457e5_0
- gstreamer=1.12.2=h4f93127_0
- html5lib=0.9999999=py27_0
- icu=58.2=h211956c_0
- intel-openmp=2018.0.0=h15fc484_7
- ipykernel=4.6.1=py27hc93e584_0
- ipython=5.4.1=py27h36c99b6_1
- ipython_genutils=0.2.0=py27h89fb69b_0
- ipywidgets=7.0.0=py27h4fda95d_0
- jinja2=2.9.6=py27h82327ae_1
- jpeg=9b=habf39ab_1
- jsonschema=2.6.0=py27h7ed5aa4_0
- jupyter=1.0.0=py27h505fd4b_0
- jupyter_client=5.1.0=py27hbee1118_0
- jupyter_console=5.2.0=py27hc6bee7e_1
- jupyter_core=4.3.0=py27hcd9ae3a_0
- libedit=3.1=heed3624_0
- libffi=3.2.1=h4deb6c0_3
- libgcc-ng=7.2.0=h7cc24e2_2
- libpng=1.6.32=hda9c8bc_2
- libprotobuf=3.4.0=0
- libsodium=1.0.13=h31c71d8_2
- libstdcxx-ng=7.2.0=h7a57d05_2
- libtiff=4.0.8=h90200ff_9
- libxcb=1.12=he6ee5dd_2
- libxml2=2.9.4=h6b072ca_5
- libxslt=1.1.29=hcf9102b_5
- lxml=3.8.0=py27hb3ac1f5_0
- markdown=2.6.9=py27_0
- markupsafe=1.0=py27h97b2822_1
- matplotlib=2.1.0=py27h09aba24_0
- mistune=0.7.4=py27h6da7e90_0
- mkl=2018.0.0=hb491cac_4
- mock=2.0.0=py27_0
- nbconvert=5.3.1=py27he041f76_0
- nbformat=4.4.0=py27hed7f2b2_0
- ncurses=6.0=h06874d7_1
- notebook=5.0.0=py27h3661c2b_2
- numpy=1.13.3=py27hbcc08e0_0
- olefile=0.44=py27h4bd3e3c_0
- openssl=1.0.2l=h9d1a558_3
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py27h428e1e5_1
- pathlib2=2.3.0=py27h6e9d198_0
- pbr=3.1.1=py27hf64632f_0
- pcre=8.41=hc71a17e_0
- pexpect=4.2.1=py27hcf82287_0
- pickleshare=0.7.4=py27h09770e1_0
- pillow=4.2.1=py27h7cd2321_0
- pip=9.0.1=py27hbf658b2_3
- prompt_toolkit=1.0.15=py27h1b593e1_0
- protobuf=3.4.0=py27_0
- ptyprocess=0.5.2=py27h4ccb14c_0
- pygments=2.2.0=py27h4a8b6f5_0
- pyparsing=2.2.0=py27hf1513f8_1
- pyqt=5.6.0=py27h4b1e83c_5
- python=2.7.14=h1aa7481_19
- python-dateutil=2.6.1=py27h4ca5741_1
- pytz=2017.2=py27hcac29fa_1
- pyyaml=3.12=py27h2d70dd7_1
- pyzmq=16.0.2=py27h297844f_2
- qt=5.6.2=h974d657_12
- qtconsole=4.3.1=py27hc444b0d_0
- readline=7.0=hac23ff0_3
- scandir=1.5=py27h1c9e1f8_1
- setuptools=36.5.0=py27h68b189e_0
- simplegeneric=0.8.1=py27h19e43cd_0
- singledispatch=3.4.0.3=py27h9bcb476_0
- sip=4.18.1=py27he9ba0ab_2
- six=1.10.0=py27hdcd7534_1
- sqlite=3.20.1=h6d8b0f3_1
- ssl_match_hostname=3.5.0.1=py27h4ec10b9_2
- subprocess32=3.2.7=py27h373dbce_0
- tensorflow=1.3.0=0
- tensorflow-base=1.3.0=py27_0
- tensorflow-tensorboard=0.1.5=py27_0
- terminado=0.6=py27h4be8df9_0
- testpath=0.3.1=py27hc38d2c4_0
- tk=8.6.7=h5979e9b_1
- tornado=4.5.2=py27h97b179f_0
- traitlets=4.3.2=py27hd6ce930_0
- wcwidth=0.1.7=py27h9e3e1ab_0
- werkzeug=0.12.2=py27hbf75dff_0
- wheel=0.29.0=py27h411dd7b_1
- widgetsnbextension=3.0.2=py27hcb77dec_1
- xz=5.2.3=h2bcbf08_1
- yaml=0.1.7=h96e3832_1
- zeromq=4.2.2=hb0b69da_1
- zlib=1.2.11=hfbfcf68_1
- pip:
  - backports-abc==0.5
  - backports.functools-lru-cache==1.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15
  - tensorflow-gpu==1.3.0

